// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/server.h"
#include "example.pb_msg.h"

namespace examplepb {
    struct RPCServer;

    struct RPCServer : serialrpc::ServerBase {
        explicit RPCServer(SumService &sum_service, CANService &can_service, ExampleService &example_service);

        void send_SumService_sum_events(SumEvent const &msg);

        SumService& sum_service;

        CANService& can_service;

        ExampleService& example_service;

        void handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) override;

        void unsubscribe_all() override;
    };
}
