// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace serialrpc {
    void SumRequest::marshal(SumRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.LeftFieldNumber, req.left, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.RightFieldNumber, req.right, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumRequest SumRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case LeftFieldNumber:
                msg.left = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            case RightFieldNumber:
                msg.right = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumRequest::operator==(const SumRequest& other) const {
        return left == other.left
            && right == other.right;
    }

    void SumResponse::marshal(SumResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AnswerFieldNumber, req.answer, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumResponse SumResponse::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumResponse msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AnswerFieldNumber:
                msg.answer = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumResponse::operator==(const SumResponse& other) const {
        return answer == other.answer;
    }

    void SumEventsRequest::marshal(SumEventsRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.VFieldNumber, req.v, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumEventsRequest SumEventsRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumEventsRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case VFieldNumber:
                msg.v = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumEventsRequest::operator==(const SumEventsRequest& other) const {
        return v == other.v;
    }

    void SumEvent::marshal(SumEvent const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.EventFieldNumber, req.event, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumEvent SumEvent::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumEvent msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case EventFieldNumber:
                msg.event = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumEvent::operator==(const SumEvent& other) const {
        return event == other.event;
    }

    void Message2::marshal(Message2 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.SumRequestFieldNumber, req.sum_request, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    Message2 Message2::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        Message2 msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case SumRequestFieldNumber:
                msg.sum_request = serialrpc::unmarshal<serialrpc::SumRequest>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool Message2::operator==(const Message2& other) const {
        return sum_request == other.sum_request;
    }


    RPCServer::RPCServer(SumService &sum_service)
        : sum_service(sum_service)
    {}

    void RPCServer::send_SumService_sum_events(SumEvent const &msg) {
        this->send_event(1, msg);
    }

    void RPCServer::handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) {
        switch (rpc_id) {
        case 1: {
            SumRequest msg = serialrpc::unmarshal<SumRequest>(conn, err);
            if (err) {
                return;
            }
            SumResponse resp = sum_service.sum(msg, RPCServer::ServerErrorHandler(conn, err));
            if (err) {
                return;
            }
            send_reply(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 2: {
            bool enabled = conn.read_byte(err);
            if (err) {
                return;
            }
            if (enabled) {
                SumEventsRequest msg = serialrpc::unmarshal<SumEventsRequest>(conn, err);
                if (err) {
                    return;
                }
                sum_service.subscribe_sum_events(*this, msg);
            } else {
                sum_service.unsubscribe_sum_events();
            }
            send_code(conn, serialrpc::Reply, err);
            if (err) {
                return;
            }
            break;
        }
        default:
            send_code(conn, serialrpc::Unknown, err);
        } // switch
    }

    void RPCServer::unsubscribe_all() {
        this->sum_service.unsubscribe_sum_events();
    }

    RPCClient::RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn)
        : ClientBase(conn)
        , sum_service(*this)
    {}

    RPCClient::SumServiceStub::SumServiceStub(RPCClient &client)
        : client(client)
    {}

    SumResponse RPCClient::SumServiceStub::sum(SumRequest const &req, lib::error err) {
        return this->client.call<SumRequest const&, SumResponse>(1, req, err);
    }

    void RPCClient::SumServiceStub::subscribe_sum_events(SumEventsRequest const &req, std::function<void(SumEvent const&)> const &cb, lib::error err) {
        sync::Lock lock(this->mtx);
        this->sum_events_cb = cb;
        this->client.subscribe(2, req, err);
    }

    void RPCClient::SumServiceStub::unsubscribe_sum_events(lib::error err) {
        sync::Lock lock(this->mtx);
        this->client.unsubscribe(2, err);
        if (err) {
            return;
        }
        this->sum_events_cb = {};
    }

    void RPCClient::SumServiceStub::handle_sum_events(SumEvent const &msg) {
        sync::Lock lock(this->mtx);
        if (this->sum_events_cb) {
            this->sum_events_cb(msg);
        }
    }

    void RPCClient::handle_event(lib::uint32 event_id, lib::error err) {
        switch (event_id) {
        case 1: {
            SumEvent msg = serialrpc::unmarshal<SumEvent>(*this->conn, err);
            if (err) {
                return;
            }
            this->sum_service.handle_sum_events(msg);
            break;
        }
        default:
            err("unknown event");
        } // switch
    }
}
