// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/client.h"
#include "example.pb_msg.h"

namespace examplepb {
    struct RPCServer;

    struct RPCClient : serialrpc::ClientBase {
        explicit RPCClient();

        explicit RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn);

        struct SumServiceStub {
            static constexpr char ServiceName[] = "SumService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            std::function<void(SumEvent const&)> sum_events_cb;

            explicit SumServiceStub(RPCClient &client);

            SumResponse sum(SumRequest const &req, lib::error err);

            void subscribe_sum_events(SumEventsRequest const &req, std::function<void(SumEvent const&)> const &cb, lib::error err);

            void unsubscribe_sum_events(lib::error err);

            void handle_sum_events(SumEvent const &msg);
        } sum_service;

        struct CANServiceStub {
            static constexpr char ServiceName[] = "CANService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            explicit CANServiceStub(RPCClient &client);

            void send(CANFrame const &req, lib::error err);
        } can_service;

        struct ExampleServiceStub {
            static constexpr char ServiceName[] = "ExampleService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            explicit ExampleServiceStub(RPCClient &client);

            void say_hello(lib::error err);
        } example_service;

        void handle_event(lib::uint32 event_id, lib::error err) override;
    };
}
