// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_msg.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace examplepb {
    void SumRequest::marshal(SumRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.LeftFieldNumber, req.left, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.RightFieldNumber, req.right, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumRequest SumRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case LeftFieldNumber:
                msg.left = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            case RightFieldNumber:
                msg.right = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumRequest::operator==(const SumRequest& other) const {
        return left == other.left
            && right == other.right;
    }

    void SumResponse::marshal(SumResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AnswerFieldNumber, req.answer, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumResponse SumResponse::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumResponse msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AnswerFieldNumber:
                msg.answer = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumResponse::operator==(const SumResponse& other) const {
        return answer == other.answer;
    }

    void SumEventsRequest::marshal(SumEventsRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.VFieldNumber, req.v, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumEventsRequest SumEventsRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumEventsRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case VFieldNumber:
                msg.v = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumEventsRequest::operator==(const SumEventsRequest& other) const {
        return v == other.v;
    }

    void SumEvent::marshal(SumEvent const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.EventFieldNumber, req.event, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SumEvent SumEvent::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SumEvent msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case EventFieldNumber:
                msg.event = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SumEvent::operator==(const SumEvent& other) const {
        return event == other.event;
    }

    void Message2::marshal(Message2 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.SumRequestFieldNumber, req.sum_request, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    Message2 Message2::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        Message2 msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case SumRequestFieldNumber:
                msg.sum_request = serialrpc::unmarshal<examplepb::SumRequest>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<8>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool Message2::operator==(const Message2& other) const {
        return sum_request == other.sum_request
            && data == other.data;
    }

    void CANFrame::marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.FrameIdFieldNumber, req.frame_id, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    CANFrame CANFrame::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CANFrame msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case FrameIdFieldNumber:
                msg.frame_id = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<8>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CANFrame::operator==(const CANFrame& other) const {
        return frame_id == other.frame_id
            && data == other.data;
    }



}
