// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/encoding.h"

namespace examplepb {
    struct RPCServer;

    struct SumRequest {
        static void marshal(SumRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SumRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SumRequest& other) const;

        int32_t left = {};

        int32_t right = {};

        static const uint32_t LeftFieldNumber = 1;

        static const uint32_t RightFieldNumber = 2;
    };

    struct SumResponse {
        static void marshal(SumResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SumResponse unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SumResponse& other) const;

        int32_t answer = {};

        static const uint32_t AnswerFieldNumber = 1;
    };

    struct SumEventsRequest {
        static void marshal(SumEventsRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SumEventsRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SumEventsRequest& other) const;

        int32_t v = {};

        static const uint32_t VFieldNumber = 1;
    };

    struct SumEvent {
        static void marshal(SumEvent const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SumEvent unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SumEvent& other) const;

        int32_t event = {};

        static const uint32_t EventFieldNumber = 1;
    };

    struct Message2 {
        static void marshal(Message2 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static Message2 unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const Message2& other) const;

        SumRequest sum_request = {};

        lib::InlineString<8> data = {};

        static const uint32_t SumRequestFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;
    };

    struct CANFrame {
        static void marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CANFrame unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CANFrame& other) const;

        uint32_t frame_id = {};

        lib::InlineString<8> data = {};

        static const uint32_t FrameIdFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;
    };

    struct SumService {
        virtual SumResponse sum(SumRequest const &req, lib::error err) = 0;

        virtual void subscribe_sum_events(RPCServer &server, SumEventsRequest const &req, lib::error err) = 0;

        virtual void unsubscribe_sum_events() = 0;
    };

    struct CANService {
        virtual void send(CANFrame const &req, lib::error err) = 0;
    };

    struct ExampleService {
        virtual void say_hello(lib::error err) = 0;
    };
}
