// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_server.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace examplepb {
    RPCServer::RPCServer(SumService &sum_service, CANService &can_service, ExampleService &example_service)
        : sum_service(sum_service)
        , can_service(can_service)
        , example_service(example_service)
    {}

    void RPCServer::send_SumService_sum_events(SumEvent const &msg) {
        this->send_event(1, msg);
    }

    void RPCServer::handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) {
        switch (rpc_id) {
        case 1: {
            SumRequest msg = serialrpc::unmarshal<SumRequest>(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            SumResponse resp = sum_service.sum(msg, handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 2: {
            bool enabled = conn.read_byte(err);
            if (err) {
                return;
            }
            if (enabled) {
                SumEventsRequest msg = serialrpc::unmarshal<SumEventsRequest>(conn, err);
                if (err) {
                    return;
                }
                RPCServer::ServerErrorHandler handler_err(*this, err);
                sum_service.subscribe_sum_events(*this, msg, handler_err);
                if (err || handler_err) {
                    return;
                }
            } else {
                sum_service.unsubscribe_sum_events();
            }
            send_code(conn, serialrpc::Reply, err);
            if (err) {
                return;
            }
            break;
        }
        case 3: {
            CANFrame msg = serialrpc::unmarshal<CANFrame>(conn, err);
            if (err) {
                return;
            }
            can_service.send(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 4: {
            serialrpc::skip(conn, err);
            if (err) {
                return;
            }
            example_service.say_hello(RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        default:
            send_code(conn, serialrpc::Unknown, err);
        } // switch
    }

    void RPCServer::unsubscribe_all() {
        this->sum_service.unsubscribe_sum_events();
    }
}
