// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_client.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace examplepb {
    RPCClient::RPCClient()
        : ClientBase()
        , sum_service(*this)
        , can_service(*this)
        , example_service(*this)
    {}

    RPCClient::RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn)
        : ClientBase(conn)
        , sum_service(*this)
        , can_service(*this)
        , example_service(*this)
    {}

    RPCClient::SumServiceStub::SumServiceStub(RPCClient &client)
        : client(client)
    {}

    SumResponse RPCClient::SumServiceStub::sum(SumRequest const &req, lib::error err) {
        return this->client.call<SumRequest const&, SumResponse>(1, ServiceName, "sum", req, err);
    }

    void RPCClient::SumServiceStub::subscribe_sum_events(SumEventsRequest const &req, std::function<void(SumEvent const&)> const &cb, lib::error err) {
        {
            sync::Lock lock(this->mtx);
            this->sum_events_cb = cb;
        }
        this->client.subscribe(2, ServiceName, "sum_events", req, err);
    }

    void RPCClient::SumServiceStub::unsubscribe_sum_events(lib::error err) {
        sync::Lock lock(this->mtx);
        this->client.unsubscribe(2, ServiceName, "sum_events", err);
        if (err) {
            return;
        }
        this->sum_events_cb = {};
    }

    void RPCClient::SumServiceStub::handle_sum_events(SumEvent const &msg) {
        sync::Lock lock(this->mtx);
        if (this->sum_events_cb) {
            this->sum_events_cb(msg);
        }
    }

    RPCClient::CANServiceStub::CANServiceStub(RPCClient &client)
        : client(client)
    {}

    void RPCClient::CANServiceStub::send(CANFrame const &req, lib::error err) {
        this->client.call_void<CANFrame const&>(3, ServiceName, "send", req, err);
    }

    RPCClient::ExampleServiceStub::ExampleServiceStub(RPCClient &client)
        : client(client)
    {}

    void RPCClient::ExampleServiceStub::say_hello(lib::error err) {
        this->client.call_void(4, ServiceName, "say_hello", err);
    }

    void RPCClient::handle_event(lib::uint32 event_id, lib::error err) {
        switch (event_id) {
        case 1: {
            SumEvent msg = serialrpc::unmarshal<SumEvent>(*this->conn, err);
            if (err) {
                return;
            }
            this->sum_service.handle_sum_events(msg);
            break;
        }
        default:
            err("unknown event");
        } // switch
    }
}
