// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialrpc.proto
// Protobuf C++ Version: 6.32.1

#include "serialrpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
template <typename>
PROTOBUF_CONSTEXPR Nothing::Nothing(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(Nothing_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NothingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NothingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NothingDefaultTypeInternal() {}
  union {
    Nothing _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NothingDefaultTypeInternal _Nothing_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_serialrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_serialrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_serialrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Nothing)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_Nothing_default_instance_._instance,
};
const char descriptor_table_protodef_serialrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017serialrpc.proto\032 google/protobuf/descr"
    "iptor.proto\"\t\n\007Nothing:4\n\013string_size\022\035."
    "google.protobuf.FieldOptions\030\320\206\003 \001(\r:3\n\n"
    "bytes_size\022\035.google.protobuf.FieldOption"
    "s\030\321\206\003 \001(\r:3\n\narray_size\022\035.google.protobu"
    "f.FieldOptions\030\322\206\003 \001(\r:5\n\nservice_id\022\037.g"
    "oogle.protobuf.ServiceOptions\030\320\206\003 \001(\r:3\n"
    "\tmethod_id\022\036.google.protobuf.MethodOptio"
    "ns\030\320\206\003 \001(\rB4\n\035com.philips.emil.protobufE"
    "choB\023EchoAttributesProtob\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_serialrpc_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_serialrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_serialrpc_2eproto = {
    false,
    false,
    392,
    descriptor_table_protodef_serialrpc_2eproto,
    "serialrpc.proto",
    &descriptor_table_serialrpc_2eproto_once,
    descriptor_table_serialrpc_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_serialrpc_2eproto::offsets,
    file_level_enum_descriptors_serialrpc_2eproto,
    file_level_service_descriptors_serialrpc_2eproto,
};
// ===================================================================

class Nothing::_Internal {
 public:
};

Nothing::Nothing(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, Nothing_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Nothing)
}
Nothing::Nothing(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Nothing& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, Nothing_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Nothing* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Nothing)
}

inline void* PROTOBUF_NONNULL Nothing::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Nothing(arena);
}
constexpr auto Nothing::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Nothing),
                                            alignof(Nothing));
}
constexpr auto Nothing::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Nothing_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Nothing::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Nothing>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Nothing::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Nothing>(), &Nothing::ByteSizeLong,
              &Nothing::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Nothing, _impl_._cached_size_),
          false,
      },
      &Nothing::kDescriptorMethods,
      &descriptor_table_serialrpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Nothing_class_data_ =
        Nothing::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Nothing::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Nothing_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Nothing_class_data_.tc_table);
  return Nothing_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
Nothing::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Nothing_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nothing>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata Nothing::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        string_size(kStringSizeFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        bytes_size(kBytesSizeFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        array_size(kArraySizeFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::ServiceOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        service_id(kServiceIdFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::MethodOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        method_id(kMethodIdFieldNumber, 0u);
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_serialrpc_2eproto),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50000, 13,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50001, 13,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50002, 13,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::ServiceOptions::default_instance(), 50000, 13,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::MethodOptions::default_instance(), 50000, 13,
            false, false),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
