// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_client.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace pb {
    RPCClient::RPCClient()
        : ClientBase()
    {}

    RPCClient::RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn)
        : ClientBase(conn)
    {}

    void RPCClient::handle_event(lib::uint32 event_id, lib::error err) {
        switch (event_id) {
        default:
            err("unknown event");
        } // switch
    }
}
