// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_server.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace pb {
    RPCServer::RPCServer()
    {}

    void RPCServer::handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) {
        switch (rpc_id) {
        default:
            send_code(conn, serialrpc::Unknown, err);
        } // switch
    }

    void RPCServer::unsubscribe_all() {}
}
