// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/encoding.h"

namespace pb {
    struct RPCServer;

    enum class Enum1 {
        EnumField = 0
    };

    struct Msg1 {
        static void marshal(Msg1 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static Msg1 unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const Msg1& other) const;

        int32_t field1 = {};

        static const uint32_t Field1FieldNumber = 1;
    };

    struct Msg2 {
        enum EmbeddedEnum {
            EnumField = 0
        };

        static void marshal(Msg2 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static Msg2 unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const Msg2& other) const;

        int32_t field1 = {};

        EmbeddedEnum field2 = {};

        static const uint32_t Field1FieldNumber = 1;

        static const uint32_t Field2FieldNumber = 2;
    };
}
