// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb_msg.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace pb {
    void Msg1::marshal(Msg1 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.Field1FieldNumber, req.field1, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    Msg1 Msg1::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        Msg1 msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case Field1FieldNumber:
                msg.field1 = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool Msg1::operator==(const Msg1& other) const {
        return field1 == other.field1;
    }

    void Msg2::marshal(Msg2 const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.Field1FieldNumber, req.field1, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Field2FieldNumber, int32(req.field2), err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    Msg2 Msg2::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        Msg2 msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case Field1FieldNumber:
                msg.field1 = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            case Field2FieldNumber:
                msg.field2 = (EmbeddedEnum) serialrpc::unmarshal<int32>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool Msg2::operator==(const Msg2& other) const {
        return field1 == other.field1
            && field2 == other.field2;
    }
}
