// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/client.h"
#include "example.pb_msg.h"

namespace pb {
    struct RPCServer;

    struct RPCClient : serialrpc::ClientBase {
        explicit RPCClient();

        explicit RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn);

        void handle_event(lib::uint32 event_id, lib::error err) override;
    };
}
